//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salones_empresariales_xyz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public System.DateTime FECHA { get; set; }
        public string CANTIDAD_PERSONAS { get; set; }
        public string MOTIVO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO { get; set; }
        public int CLIENTE_ID { get; set; }
        public int ID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
